config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, only: [:new, :create, :edit, :show, :update, :destroy]

end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord

    validates :name, presence: true
    
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

    attr_reader :password
    after_initialize :ensure_session_token

    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true


    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save! 
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        pass_obj = BCrypt::Password.new(self.password_digest)
        pass_obj.is_password?(password)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)

        if user && user.is_password?(password)
            user
        else 
            nil
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @bands = Band.all
        render :index
    end

    def new
        render :new
    end

    def create
        @band = Band.new(band_params)

        if @band.save
            redirect_to band_url(@band)
        else
            render json: @band.errors.full_messages, status: :unprocessable_entity
        end
    end

    def show
        @band = Band.find(params[:id])

        if @band
            render :show
        else
            render json: "Not found", status: 404
        end
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def update
        @band = Band.find(params[:id])

        if @band.update(band_params)
            redirect_to band_url(@band)
        else
            render json: @band.errors.full_messages, status: :unprocessable_entity
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url

    end

    def band_params
        params.require(:band).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:email],params[:user][:password])

        if @user
            login(@user)
            redirect_to user_url(@user)
        else
            @user = User.new
            flash.now[:errors] = ["invalid credentials"]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else
            render json: @user.errors.full_messages, status: :unprocessable_entity
        end
    end

    def user_params
        params.require(:user).permit(:email, :password)
    end

    def show
        @user = User.find(params[:id])

        render :show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/edit.html.erb
<h2>Edit Band Name</h2>


<form action="<%= band_url %>" method="post">
<input type="hidden" name="_method" value="patch">
<input type="hidden" name="authenticity_token" value="form_authenticity_token">
<label> Band Name:
<input type="text" name="band[name]" value="<%= @band.name %>">
</label>

<input type="submit" value="Edit Band Name">

</form>

app/views/bands/index.html.erb
<h2>All the Bands</h2>

<ul>
    <% @bands.each do |band| %>
    <li><%= band.name %></li>
    <% end %>
</ul>

app/views/bands/new.html.erb
<h2>Band</h2>


<form action="<%= bands_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">
<label>Band Name:
<input type="text" name="band[name]">
</label>

<input type="submit" value="Submit Band Name">

</form>

app/views/bands/show.html.erb
<h2><%= @band.name %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<% if logged_in? %>
 <h2>Welcome!</h2>
 
    <form action="<%= session_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Sign Out">
    </form>
  <% else %>
    <a href="<%= new_user_url %>">Sign Up</a>
    <a href="<%= new_session_url %>">Login</a>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h2>SIGN UP HERE!</h2>

<form action="<%= users_url %>" method="post">
<input type="hidden" name="authenticity_token" value="form_authenticity_token">
<label>Email:
    <input type="text" name="user[email]">
</label>
<br>

<label>Password:
    <input type="password" name="user[password]">   
</label>
<br>

<input type="submit" value="Create User">

</form> 

app/views/users/show.html.erb
<h2>Hello <%= @user.email %></h2>